analysis_type: asimov
llh: PoissonLLH
# detector_configs: [IC86_pass2_SnowStorm_example_tracks, arca230_numu_hori_20PeV]
detector_configs: [IC86_pass2_SnowStorm_example_tracks]
input_params:
  gamma_astro: 2.37
  astro_norm: 1.36
  # prompt_norm: 0.0
  # conv_norm: 1.0
  # all (other) nuisance parameters at default
