analysis_type: asimov
llh: PoissonLLH
detector_configs: [IC86_pass2_SnowStorm_example_tracks, arca230_numu_hori_20PeV]
input_params:
  gamma_astro: 1.54
  astro_norm: 0.077
  # prompt_norm: 0.0
  # conv_norm: 1.0
  # all (other) nuisance parameters at default
