#
# atmospheric
#

# conventional:
#   baseline_weights: &conv_base_weights mceq_conv_H4a_SIBYLL23c
#   class: ConventionalAtmo
#   parameters: [conv_norm, delta_gamma, CR_grad]
#   param_specifications:
#     delta_gamma:
#       baseline_weights: *conv_base_weights
#     CR_grad:
#       baseline_weights: *conv_base_weights
#       alternative_weights: mceq_conv_GST4_SIBYLL23c

# prompt:
#   baseline_weights: &prompt_base_weights mceq_pr_H4a_SIBYLL23c
#   class: PromptAtmo
#   parameters: [prompt_norm, delta_gamma, CR_grad]
#   param_specifications:
#     delta_gamma:
#       baseline_weights: *prompt_base_weights
#     CR_grad:
#       baseline_weights: *prompt_base_weights
#       alternative_weights: mceq_pr_GST4_SIBYLL23c

#
# astro
#

astro:
  baseline_weights: powerlaw
  class: Powerlaw
  parameters: [astro_norm, gamma_astro]
