#
# atmospheric
#

conv_norm:
  range: [0.,null]
  default: 1.02
  class: Norm

prompt_norm:
  range: [0.,null]
  default: 0.5
  class: Norm

delta_gamma:
  range: [-1., 1.]
  default:  0.
  interpolate: False
  class: DeltaGamma

muon_norm:
  range: [0, null]
  default: 1.
  class: Norm
  prior: 1.
  prior_width: 0.05

CR_grad:
  range: [-1.0, 2.0]
  default: 0.
  class: CRGrad
  prior: 0.
  prior_width: 1.

#
# astro
#

astro_norm:
  default: 0.75
  range: [0., null]
  interpolate: False
  class: Norm
  additional:
    per_type_norm: False

gamma_astro:
  default: 2.8
  range: [1., null]
  interpolate: False
  class: SpectralIndex
  additional:
    reference_index: 2.0
