# executable on network storage
executable = run_asimov_fit.sh

# log file on local storage
log         = /scratch/tvaneede/run_asimov_fit_log_$(Cluster)_$(Process).txt
error       = /scratch/tvaneede/run_asimov_fit_error_$(Cluster)_$(Process).txt
notification = never

# output files on network file storage
output = run_asimov_fit.out

transfer_input_files = /mnt/ceph1-npx/user/tvaneede/software/NNMFit/NNMFit/scripts/run_fit.py /data/user/tvaneede/GlobalFit/analysis/track_6yr_test/configs/main_SPL.cfg /data/user/tvaneede/GlobalFit/analysis/track_6yr_test/configs/analysis_configs/asimov_SPL.yaml

should_transfer_files = YES

request_cpus = 1
request_memory = 8GB
request_disk = 1GB

queue 1
